/**
 * The training seam: plans, goal races and the athlete's schedule.
 *
 * One slice rather than three, because the three are read together on every
 * screen that needs any of them — a plan card is meaningless without the race it
 * builds towards — and all three are small enough to hold open at once.
 *
 * The split that matters here is authorship, not size. Plans and races are
 * generated by the backend and the client only reads them; the schedule is the
 * athlete's own and is the one thing this service writes.
 */
import type { DateKey, Discipline } from '@/domain/training';
import type { RaceDraft } from '@/services/onboarding';

/** Where a plan sits relative to today. */
export type PlanStatus = 'current' | 'upcoming' | 'complete';

export type PlanModel = {
  id: string;
  /** 'Prep Plan', 'Race Plan' — the name the card leads with. */
  name: string;
  status: PlanStatus;
  /** 'Base Phase', 'Build', 'Peak'. Null before a plan has begun. */
  phase: string | null;
  startDate: DateKey;
  endDate: DateKey;
  /** Total weeks the plan runs for. */
  weeks: number;
  /**
   * Planned hours per week, one entry per week of the plan.
   *
   * Denormalised onto the plan rather than derived from its sessions, so the
   * dashboard's chart costs one document read instead of fanning out over a
   * year of sessions the client has no other reason to fetch.
   */
  weeklyPlannedHours: number[];
  /** Index into `weeklyPlannedHours`. Null for a plan not yet under way. */
  currentWeekIndex: number | null;
  /** How much of the current week is done, 0-1. Null when not under way. */
  currentWeekProgress: number | null;
  /** The race this plan builds towards. */
  raceId: string | null;
  artworkUrl: string | null;
};

/** One leg of a multi-sport race. */
export type RaceLeg = { discipline: Discipline; distanceMetres: number };

export type RaceModel = {
  id: string;
  /** 'IRONMAN 70.3 Luxembourg'. */
  name: string;
  place: string;
  date: DateKey;
  /** A races, B races and C races — the design's priority ladder. */
  priority: 'A' | 'B' | 'C';
  legs: RaceLeg[];
  /** The athlete's goal time, in seconds. Null when they have not set one. */
  targetSeconds: number | null;
  artworkUrl: string | null;
};

/** A recurring commitment that the plan has to work around. */
export type Commitment = {
  id: string;
  label: string;
  /** 0 is Sunday, matching `Date.prototype.getDay`. */
  weekday: number;
  discipline: Discipline | null;
};

export type ScheduleModel = {
  /** Minutes the athlete can train, per weekday, indexed 0 (Sunday) to 6. */
  availableMinutes: number[];
  commitments: Commitment[];
  modifiedAt: Date | null;
};

/** What a caller may change. The timestamps are the server's. */
export type ScheduleDraft = {
  availableMinutes: number[];
  commitments: Commitment[];
};

export interface TrainingService {
  /** Plans that are current or still ahead. Read-only: the backend writes them. */
  subscribePlans(
    uid: string,
    onPlans: (plans: PlanModel[]) => void,
    onError: (error: Error) => void,
  ): () => void;

  /** Goal races, soonest first. Read-only. */
  subscribeRaces(
    uid: string,
    onRaces: (races: RaceModel[]) => void,
    onError: (error: Error) => void,
  ): () => void;

  /** The single schedule document. Null when the athlete has not set one up. */
  subscribeSchedule(
    uid: string,
    onSchedule: (schedule: ScheduleModel | null) => void,
    onError: (error: Error) => void,
  ): () => void;

  /** The athlete's own data, and so the only write in this slice. */
  updateSchedule(uid: string, changes: Partial<ScheduleDraft>): Promise<void>;

  /**
   * Deletes every plan the athlete has, and with it every session those plans
   * generated. The one exception to "plans are read-only": it only ever
   * empties the collection for a fresh plan to be generated into, never
   * creates or edits one. Races and recorded activities are untouched.
   */
  resetPlans(uid: string): Promise<void>;

  /**
   * Adds a plan for an athlete who already has a profile.
   *
   * The other exception to "plans are read-only", and a narrow one: it takes a
   * race or nothing at all, and the backend generates the plan from that and
   * the athlete's stored schedule. A caller still cannot say what a plan
   * contains.
   *
   * The new plan queues behind whatever is already running rather than
   * replacing it, so adding a spring race does not throw away the build
   * under way.
   */
  createPlan(uid: string, race: RaceDraft | null): Promise<void>;
}
