-- Plans, the races they build towards, and the athlete's weekly schedule.
--
-- Authorship divides these. Plans and races are generated by the backend and
-- read-only to the client; the schedule is the athlete's own and is the only
-- thing here they write. See docs/api.md.

-- ─── races ───────────────────────────────────────────────────────────────────

create table races (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid        not null references users(id) on delete cascade,
  name           text        not null check (length(name) between 1 and 200),
  place          text        not null default '',
  -- A race happens on a calendar day, not at an instant.
  date           date        not null,
  priority       text        not null check (priority in ('A', 'B', 'C')),
  -- The athlete's goal time. Null until they set one.
  target_seconds integer     check (target_seconds is null or target_seconds > 0),
  artwork_url    text,
  created_at     timestamptz not null default now(),
  modified_at    timestamptz not null default now()
);

-- Serves the only query: this athlete's races, soonest first.
create index races_user_date_idx on races (user_id, date);

create trigger races_touch before update on races
  for each row execute function touch_modified_at();

/*
 * A child table rather than jsonb: each leg is two meaningful values, and
 * "total distance across an athlete's A races" is the sort of question this
 * shape answers with a sum instead of an application loop.
 */
create table race_legs (
  race_id         uuid     not null references races(id) on delete cascade,
  -- Race order — swim, then bike, then run. Part of the key, so ordering is
  -- stored rather than inferred.
  position        smallint not null check (position >= 0),
  discipline      text     not null check (discipline in ('swim', 'run', 'ride', 'weights')),
  distance_metres integer  not null check (distance_metres > 0),

  primary key (race_id, position)
);

-- ─── plans ───────────────────────────────────────────────────────────────────

create table plans (
  id                    uuid        primary key default gen_random_uuid(),
  user_id               uuid        not null references users(id) on delete cascade,
  -- The race survives its plan being deleted, and a plan may have no race.
  race_id               uuid        references races(id) on delete set null,
  name                  text        not null check (length(name) between 1 and 100),
  status                text        not null check (status in ('current', 'upcoming', 'complete')),
  phase                 text,
  start_date            date        not null,
  end_date              date        not null,
  weeks                 smallint    not null check (weeks > 0),
  /*
   * A Postgres array rather than a `plan_weeks` table. Unlike the legs above,
   * these are one number per position, always read whole to draw a chart, and
   * never queried individually — so a table would add a join and a sort to
   * reconstruct something the array already stores in order.
   */
  weekly_planned_hours  real[]      not null default '{}',
  -- 0-based index into the array above. Null before a plan is under way.
  current_week_index    smallint    check (current_week_index >= 0),
  current_week_progress real        check (current_week_progress between 0 and 1),
  artwork_url           text,
  created_at            timestamptz not null default now(),
  modified_at           timestamptz not null default now(),

  constraint plans_dates_ordered check (end_date >= start_date),
  -- Progress is meaningless without a week to attach it to.
  constraint plans_progress_needs_week
    check ((current_week_index is null) = (current_week_progress is null))
);

-- The dashboard's read: this athlete's current and upcoming plans, in order.
create index plans_user_status_idx on plans (user_id, status, start_date);

create trigger plans_touch before update on plans
  for each row execute function touch_modified_at();

-- ─── schedule ────────────────────────────────────────────────────────────────

-- One row per athlete, keyed by them: there is exactly one schedule.
create table schedules (
  user_id           uuid        primary key references users(id) on delete cascade,
  -- Seven entries, index 0 = Sunday, matching Date.prototype.getDay. The
  -- constraint is what stops a weekday index running off the end of it.
  available_minutes integer[]   not null,
  modified_at       timestamptz not null default now(),

  constraint schedules_seven_days check (array_length(available_minutes, 1) = 7)
);

create trigger schedules_touch before update on schedules
  for each row execute function touch_modified_at();

create table commitments (
  id         uuid     primary key default gen_random_uuid(),
  user_id    uuid     not null references users(id) on delete cascade,
  label      text     not null check (length(label) between 1 and 100),
  weekday    smallint not null check (weekday between 0 and 6),
  discipline text     check (discipline in ('swim', 'run', 'ride', 'weights'))
);

create index commitments_user_idx on commitments (user_id, weekday);
