-- The plan's sessions, and the shape of each one over time.
--
-- Generated by the backend. The client reads a window of them and may set one
-- field: whether it was completed. See docs/api.md.

create table sessions (
  id                 uuid        primary key default gen_random_uuid(),
  user_id            uuid        not null references users(id) on delete cascade,
  -- A session belongs to the plan that produced it, and goes when it goes.
  plan_id            uuid        references plans(id) on delete cascade,

  /*
   * A real `date`, not a timestamp. A session belongs to a calendar day in the
   * athlete's own timezone, so storing an instant would let a flight move
   * Tuesday's long run onto Monday. The driver is told to hand this back as a
   * plain 'YYYY-MM-DD' string — see the type parser in src/db.ts.
   */
  date               date        not null,
  -- `order` is reserved; this is the position within the day.
  position           smallint    not null default 0 check (position >= 0),

  title              text        not null check (length(title) between 1 and 200),
  discipline         text        not null check (discipline in ('swim', 'run', 'ride', 'weights')),
  purpose            text        check (purpose in ('recovery', 'endurance', 'speed', 'commitment')),
  -- Technique tags and kit. Arrays: read whole, never queried individually.
  focus              text[]      not null default '{}',
  equipment          text[]      not null default '{}',
  descriptor         text,

  /*
   * Targets, flattened into columns rather than a jsonb blob. Trends is the
   * reason: "planned hours this month" is a sum over a column and an index
   * away, where inside jsonb it is a scan.
   */
  duration_seconds   integer     check (duration_seconds is null or duration_seconds > 0),
  distance_metres    integer     check (distance_metres is null or distance_metres > 0),
  pace_seconds_per_km real       check (pace_seconds_per_km is null or pace_seconds_per_km > 0),
  load               real        check (load is null or load between 0 and 10),
  estimated          boolean     not null default false,

  -- Chart axis length, held apart from the duration so a long cool-down does
  -- not shrink the axis to the last effort.
  chart_seconds      integer     check (chart_seconds is null or chart_seconds > 0),
  tick_every_minutes smallint    check (tick_every_minutes is null or tick_every_minutes > 0),

  -- The only two columns a client may change, and only through the completion
  -- route. Server-assigned: a wrong phone clock cannot backdate a session.
  completed_at       timestamptz,
  completion_activity_id uuid,

  coach_name         text,
  coach_note         text,
  created_at         timestamptz not null default now(),
  modified_at        timestamptz not null default now(),

  -- Two sessions on one day must not claim the same slot.
  unique (user_id, date, position)
);

-- The windowed read: this athlete's sessions between two dates, in order.
create index sessions_user_date_idx on sessions (user_id, date, position);

create trigger sessions_touch before update on sessions
  for each row execute function touch_modified_at();

/*
 * One row per effort block.
 *
 * A child table rather than jsonb, for the same reason as race legs and more
 * so: "time spent in each zone this month" — which is what Trends needs and
 * Firestore could not do — is a join and a group by over this table.
 */
create table session_segments (
  session_id       uuid     not null references sessions(id) on delete cascade,
  position         smallint not null check (position >= 0),
  start_seconds    integer  not null check (start_seconds >= 0),
  duration_seconds integer  not null check (duration_seconds > 0),
  intensity        real     not null check (intensity between 0 and 1),
  zone             text     not null check (zone in
                     ('warmup', 'easy', 'hard', 'swim', 'ride', 'sprint', 'drill')),
  -- Drill work, which the chart hatches as well as colours.
  drill            boolean  not null default false,

  primary key (session_id, position)
);
