/**
 * "Calendar sync" — the state of the training calendar feed, and the two ways
 * to subscribe to it.
 *
 * Apple Calendar gets its own row because it can subscribe from a `webcal:`
 * link in one tap; everything else needs the URL copied into it, which is what
 * the second row does. Both open through `Linking`, so neither depends on a
 * backend that is not here — but the feed itself is not generated by anything
 * in this repo, so the URL is a placeholder from the local store.
 */
import { router } from 'expo-router';
import { useState } from 'react';
import { Alert, Linking, Pressable, Share, StyleSheet, View } from 'react-native';

import { Icon } from '@/components/icon';
import { SettingsModal } from '@/components/settings-modal';
import { ThemedText } from '@/components/themed-text';
import { Accents, Spacing } from '@/constants/theme';
import { useScreenTracking } from '@/hooks/use-screen-tracking';
import { useTheme } from '@/hooks/use-theme';
import { useSettings } from '@/providers/settings-provider';
import { reportError } from '@/services/telemetry';

function formatSynced(at: Date | null) {
  if (!at) {
    return 'Never synced';
  }

  const day = at.toLocaleDateString(undefined, { month: 'short', day: 'numeric' });
  const time = at.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' });
  return `Last synced: ${day} at ${time}`;
}

export default function CalendarSyncModal() {
  useScreenTracking('Calendar sync');

  const theme = useTheme();
  const { state, updateIntegrations } = useSettings();
  const calendar = state.status === 'ready' ? state.integrations.calendar : null;

  const [error, setError] = useState<string | null>(null);

  async function subscribeInApple() {
    if (!calendar?.feedUrl) {
      return;
    }

    // `webcal:` is what makes Calendar offer to subscribe rather than download
    // the file once — the same URL over https would just fetch it.
    const url = calendar.feedUrl.replace(/^https?:/, 'webcal:');
    try {
      await Linking.openURL(url);
    } catch (caught) {
      reportError(caught, 'calendar: subscribe');
      setError('Could not open Calendar.');
    }
  }

  async function shareFeed() {
    if (!calendar?.feedUrl) {
      return;
    }

    try {
      // The share sheet rather than a clipboard copy: the athlete is usually
      // moving this link to another device, which is what sharing is for.
      await Share.share({ message: calendar.feedUrl });
    } catch (caught) {
      reportError(caught, 'calendar: share');
    }
  }

  function confirmDisable() {
    Alert.alert(
      'Disable calendar sync?',
      'Your training calendar will stop updating. Any calendar already subscribed to it will go stale.',
      [
        { text: 'Cancel', style: 'cancel' },
        {
          text: 'Disable',
          style: 'destructive',
          onPress: () => {
            void updateIntegrations({ calendar: { connected: false } }).catch(() =>
              setError('Could not disable calendar sync.'),
            );
            router.back();
          },
        },
      ],
    );
  }

  return (
    <SettingsModal
      title="Calendar sync"
      icon="calendar"
      iconAccent={Accents.schedule}
      layout="panel"
      error={error}>
      <View style={styles.status}>
        <View style={styles.statusRow}>
          <View style={[styles.dot, { backgroundColor: Accents.endurance }]} />
          <ThemedText style={[styles.statusLabel, { color: Accents.endurance }]}>
            {calendar?.connected ? 'Connected' : 'Not connected'}
          </ThemedText>
        </View>
        <ThemedText themeColor="textSecondary" style={styles.blurb}>
          Your current and next training week are in your calendar, updating automatically as your
          plan changes.
        </ThemedText>
        <ThemedText themeColor="textSecondary" style={styles.synced}>
          {formatSynced(calendar?.lastSyncedAt ?? null)}
        </ThemedText>
      </View>

      <Pressable
        onPress={subscribeInApple}
        accessibilityRole="button"
        style={({ pressed }) => [
          styles.row,
          { borderColor: theme.backgroundSelected },
          pressed && styles.pressed,
        ]}>
        <Icon name="apple.logo" size={20} tintColor={theme.text} />
        <View style={styles.rowText}>
          <ThemedText style={styles.rowTitle}>Add to Apple Calendar</ThemedText>
          <ThemedText themeColor="textSecondary" style={styles.rowSub}>
            Subscribe with one tap
          </ThemedText>
        </View>
        <Icon name="chevron.right" size={14} tintColor={theme.textSecondary} />
      </Pressable>

      <Pressable
        onPress={shareFeed}
        accessibilityRole="button"
        style={({ pressed }) => [
          styles.row,
          { borderColor: theme.backgroundSelected },
          pressed && styles.pressed,
        ]}>
        <Icon name="link" size={20} tintColor={theme.text} />
        <View style={styles.rowText}>
          <ThemedText style={styles.rowTitle}>Google, Outlook and other calendars</ThemedText>
          <ThemedText themeColor="textSecondary" style={styles.rowSub}>
            Add with your private link
          </ThemedText>
        </View>
        <Icon name="chevron.right" size={14} tintColor={theme.textSecondary} />
      </Pressable>

      <Pressable
        onPress={confirmDisable}
        accessibilityRole="button"
        style={({ pressed }) => [
          styles.danger,
          { borderColor: Accents.speed, backgroundColor: `${Accents.speed}1A` },
          pressed && styles.pressed,
        ]}>
        <ThemedText style={[styles.dangerLabel, { color: Accents.speed }]}>
          Disable calendar sync
        </ThemedText>
      </Pressable>
    </SettingsModal>
  );
}

const styles = StyleSheet.create({
  status: {
    gap: Spacing.two,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.two,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  statusLabel: {
    fontSize: 17,
    fontWeight: '600',
  },
  blurb: {
    fontSize: 14,
    lineHeight: 20,
  },
  synced: {
    fontSize: 13,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.three,
    borderWidth: 1,
    borderRadius: Spacing.three,
    padding: Spacing.three,
  },
  rowText: {
    flex: 1,
  },
  rowTitle: {
    fontSize: 16,
  },
  rowSub: {
    fontSize: 13,
  },
  danger: {
    borderWidth: 1,
    borderRadius: Spacing.three,
    paddingVertical: Spacing.three,
    alignItems: 'center',
  },
  dangerLabel: {
    fontSize: 16,
    fontWeight: '600',
  },
  pressed: {
    opacity: 0.6,
  },
});
